//This code was generated by a tool as of 2007-06-08 16:53:33.718.

using System;
using System.Collections;
using Wilson.ORMapper;

namespace SimatSoft.DB.ORM
{
	public class AssetTransferDT : IObjectHelper, IObjectNotification
	{
		private string transferID;
		private int transferSeq;
		private string modelID;
		private int orderQty;
		private int transferQty;
		private decimal transferPrice;
		private decimal transferCost;
		private string remark;
		private AssetTransferHD assetTransferHDObject; // Strongly Type as AssetTransferHD if not Lazy-Loading
		//private Model modelObject; // Strongly Type as Model if not Lazy-Loading
		//private IList assetTransfers; // Supports both ObjectSet and Lazy-Loaded ObjectList
        //private IList assetTransfers; // Supports both ObjectSet and Lazy-Loaded ObjectList
        //private IList assetTransfers; // Supports both ObjectSet and Lazy-Loaded ObjectList

		public string TransferID
		{
			get { return this.transferID; }
            set { this.transferID = value; }
		}

		public int TransferSeq
		{
			get { return this.transferSeq; }
			set { this.transferSeq = value; }
		}

		public string ModelID
		{
			get { return this.modelID; }
			set { this.modelID = value; }
		}

		public int OrderQty
		{
			get { return this.orderQty; }
			set { this.orderQty = value; }
		}

		public int TransferQty
		{
			get { return this.transferQty; }
			set { this.transferQty = value; }
		}

		public decimal TransferPrice
		{
			get { return this.transferPrice; }
			set { this.transferPrice = value; }
		}

		public decimal TransferCost
		{
			get { return this.transferCost; }
			set { this.transferCost = value; }
		}

		public string Remark
		{
			get { return this.remark; }
			set { this.remark = value; }
		}

		// Return the primary key property from the primary key object
        //public AssetTransferHD AssetTransferHDObject
        //{
        //    get { return this.assetTransferHDObject; }
        //}

        //// Return the primary key property from the primary key object
        //public Model ModelObject
        //{
        //    get { return this.modelObject; }
        //}

        //public IList AssetTransfers
        //{
        //    get { return this.assetTransfers; }
        //}

        //public IList AssetTransfers
        //{
        //    get { return this.assetTransfers; }
        //}

        //public IList AssetTransfers
        //{
        //    get { return this.assetTransfers; }
        //}


		#region IObjectHelper Members
		public object this[string memberName]
		{
			get {
				switch (memberName) {
					case "transferID": return this.transferID;
					case "transferSeq": return this.transferSeq;
					case "modelID": return this.modelID;
					case "orderQty": return this.orderQty;
					case "transferQty": return this.transferQty;
					case "transferPrice": return this.transferPrice;
					case "transferCost": return this.transferCost;
					case "remark": return this.remark;
					case "assetTransferHDObject": return this.assetTransferHDObject;
					//case "modelObject": return this.modelObject;
					//case "assetTransfers": return this.assetTransfers;
					
					default: throw new Exception("Invalid Member");
				}
			}
			set {
				switch (memberName) {
					case "transferID": this.transferID = (string) value; break;
					case "transferSeq": this.transferSeq = (int) value; break;
					case "modelID": this.modelID = (string) value; break;
					case "orderQty": this.orderQty = (int) value; break;
					case "transferQty": this.transferQty = (int) value; break;
					case "transferPrice": this.transferPrice = (decimal) value; break;
					case "transferCost": this.transferCost = (decimal) value; break;
					case "remark": this.remark = (string) value; break;
                    case "assetTransferHDObject": this.assetTransferHDObject = (AssetTransferHD) value; break;
					//case "modelObject": this.modelObject = (Model) value; break;
					//case "assetTransfers": this.assetTransfers = (IList) value; break;
					
					default: throw new Exception("Invalid Member");
				}
			}
		}
		#endregion

		#region IObjectNotification Members
		public void OnCreated(Transaction transaction)
		{
			// TODO
		}

		public void OnCreating(Transaction transaction)
		{
			// TODO
		}

		public void OnDeleted(Transaction transaction)
		{
			// TODO
		}

		public void OnDeleting(Transaction transaction)
		{
			// TODO
		}

		public void OnMaterialized(System.Data.IDataRecord dataRecord)
		{
			// TODO
		}

		public void OnPersistError(Transaction transaction, Exception exception)
		{
			// TODO
		}

		public void OnUpdated(Transaction transaction)
		{
			// TODO
		}

		public void OnUpdating(Transaction transaction)
		{
			// TODO
		}
		#endregion
	}
}
