//This code was generated by a tool as of 2007-07-06 09:43:13.593.

using System;
using System.Collections;
using Wilson.ORMapper;

namespace SimatSoft.DB.ORM
{
	public class AssetTransferSerial : IObjectHelper, IObjectNotification
	{
		private int transferLine;
		private string transferID;
		private string modelID;
		private int transferSeq;
		private string assetID;
		private string fromBuildID;
		private string buildID;
		private string fromFloor;
		private string floorID;
		private string fromArea;
		private string areaID;
		private string serialID;
		private string previousCustodian;
		private string custodianID;
		private DateTime receiveDate;
		private string userName;
		private string fromFacCode;
		private string toFacCode;
		private string fromDeptID;
		private string toDeptID;
		private string remark;
        //private Area areaObject; // Strongly Type as Area if not Lazy-Loading
        //private Asset assetObject; // Strongly Type as Asset if not Lazy-Loading
        //private AssetTransfer assetTransferObject; // Strongly Type as AssetTransfer if not Lazy-Loading
        //private AssetTransfer assetTransferObject; // Strongly Type as AssetTransfer if not Lazy-Loading
        //private AssetTransfer assetTransferObject; // Strongly Type as AssetTransfer if not Lazy-Loading
		private Model modelObject; // Strongly Type as Model if not Lazy-Loading


		public string TransferID
		{
			get { return this.transferID; }
            set { this.transferID = value; }
		}

        public int TransferLine
        {
            get { return this.transferLine; }
            set { this.transferLine = value; }
        }
        
        public string ModelID
		{
			get { return this.modelID; }
			set { this.modelID = value; }
		}

		public int TransferSeq
		{
			get { return this.transferSeq; }
			set { this.transferSeq = value; }
		}

		public string AssetID
		{
			get { return this.assetID; }
			set { this.assetID = value; }
		}

		public string FromBuildID
		{
			get { return this.fromBuildID; }
			set { this.fromBuildID = value; }
		}

		public string BuildID
		{
			get { return this.buildID; }
			set { this.buildID = value; }
		}

		public string FromFloor
		{
			get { return this.fromFloor; }
			set { this.fromFloor = value; }
		}

		public string FloorID
		{
			get { return this.floorID; }
			set { this.floorID = value; }
		}

		public string FromArea
		{
			get { return this.fromArea; }
			set { this.fromArea = value; }
		}

		public string AreaID
		{
			get { return this.areaID; }
			set { this.areaID = value; }
		}

		public string SerialID
		{
			get { return this.serialID; }
			set { this.serialID = value; }
		}

		public string PreviousCustodian
		{
			get { return this.previousCustodian; }
			set { this.previousCustodian = value; }
		}

		public string CustodianID
		{
			get { return this.custodianID; }
			set { this.custodianID = value; }
		}

		public DateTime ReceiveDate
		{
			get { return this.receiveDate; }
			set { this.receiveDate = value; }
		}

		public string UserName
		{
			get { return this.userName; }
			set { this.userName = value; }
		}

		public string FromFacCode
		{
			get { return this.fromFacCode; }
			set { this.fromFacCode = value; }
		}

		public string ToFacCode
		{
			get { return this.toFacCode; }
			set { this.toFacCode = value; }
		}

		public string FromDeptID
		{
			get { return this.fromDeptID; }
			set { this.fromDeptID = value; }
		}

		public string ToDeptID
		{
			get { return this.toDeptID; }
			set { this.toDeptID = value; }
		}

		public string Remark
		{
			get { return this.remark; }
			set { this.remark = value; }
		}

        //// Return the primary key property from the primary key object
        //public Area AreaObject
        //{
        //    get { return this.areaObject; }
        //}

        //// Return the primary key property from the primary key object
        //public Asset AssetObject
        //{
        //    get { return this.assetObject; }
        //}

        //// Return the primary key property from the primary key object
        //public AssetTransfer AssetTransferObject
        //{
        //    get { return this.assetTransferObject; }
        //}

		// Return the primary key property from the primary key object
        //public AssetTransfer AssetTransferObject
        //{
        //    get { return this.assetTransferObject; }
        //}

        //// Return the primary key property from the primary key object
        //public AssetTransfer AssetTransferObject
        //{
        //    get { return this.assetTransferObject; }
        //}

		// Return the primary key property from the primary key object
		public Model ModelObject
		{
			get { return this.modelObject; }
		}


		#region IObjectHelper Members
		public object this[string memberName]
		{
			get {
				switch (memberName) {
					case "transferLine": return this.transferLine;
					case "transferID": return this.transferID;
					case "modelID": return this.modelID;
					case "transferSeq": return this.transferSeq;
					case "assetID": return this.assetID;
					case "fromBuildID": return this.fromBuildID;
					case "buildID": return this.buildID;
					case "fromFloor": return this.fromFloor;
					case "floorID": return this.floorID;
					case "fromArea": return this.fromArea;
					case "areaID": return this.areaID;
					case "serialID": return this.serialID;
					case "previousCustodian": return this.previousCustodian;
					case "custodianID": return this.custodianID;
					case "receiveDate": return this.receiveDate;
					case "userName": return this.userName;
					case "fromFacCode": return this.fromFacCode;
					case "toFacCode": return this.toFacCode;
					case "fromDeptID": return this.fromDeptID;
					case "toDeptID": return this.toDeptID;
					case "remark": return this.remark;
                    //case "areaObject": return this.areaObject;
                    //case "assetObject": return this.assetObject;
                    //case "assetTransferObject": return this.assetTransferObject;
                    //case "assetTransferObject": return this.assetTransferObject;
                    //case "assetTransferObject": return this.assetTransferObject;
                    //case "modelObject": return this.modelObject;
					default: throw new Exception("Invalid Member");
				}
			}
			set {
				switch (memberName) {
					case "transferLine": this.transferLine = (int) value; break;
					case "transferID": this.transferID = (string) value; break;
					case "modelID": this.modelID = (string) value; break;
					case "transferSeq": this.transferSeq = (int) value; break;
					case "assetID": this.assetID = (string) value; break;
					case "fromBuildID": this.fromBuildID = (string) value; break;
					case "buildID": this.buildID = (string) value; break;
					case "fromFloor": this.fromFloor = (string) value; break;
					case "floorID": this.floorID = (string) value; break;
					case "fromArea": this.fromArea = (string) value; break;
					case "areaID": this.areaID = (string) value; break;
					case "serialID": this.serialID = (string) value; break;
					case "previousCustodian": this.previousCustodian = (string) value; break;
					case "custodianID": this.custodianID = (string) value; break;
					case "receiveDate": this.receiveDate = (DateTime) value; break;
					case "userName": this.userName = (string) value; break;
					case "fromFacCode": this.fromFacCode = (string) value; break;
					case "toFacCode": this.toFacCode = (string) value; break;
					case "fromDeptID": this.fromDeptID = (string) value; break;
					case "toDeptID": this.toDeptID = (string) value; break;
					case "remark": this.remark = (string) value; break;
                    //case "areaObject": this.areaObject = (Area) value; break;
                    //case "assetObject": this.assetObject = (Asset) value; break;
                    //case "assetTransferObject": this.assetTransferObject = (AssetTransfer) value; break;
                    //case "assetTransferObject": this.assetTransferObject = (AssetTransfer) value; break;
                    //case "assetTransferObject": this.assetTransferObject = (AssetTransfer) value; break;
                    //case "modelObject": this.modelObject = (Model) value; break;
					default: throw new Exception("Invalid Member");
				}
			}
		}
		#endregion

		#region IObjectNotification Members
		public void OnCreated(Transaction transaction)
		{
			// TODO
		}

		public void OnCreating(Transaction transaction)
		{
			// TODO
		}

		public void OnDeleted(Transaction transaction)
		{
			// TODO
		}

		public void OnDeleting(Transaction transaction)
		{
			// TODO
		}

		public void OnMaterialized(System.Data.IDataRecord dataRecord)
		{
			// TODO
		}

		public void OnPersistError(Transaction transaction, Exception exception)
		{
			// TODO
		}

		public void OnUpdated(Transaction transaction)
		{
			// TODO
		}

		public void OnUpdating(Transaction transaction)
		{
			// TODO
		}
		#endregion
	}
}
