//This code was generated by a tool as of 2007-05-24 15:50:19.640.

using System;
using Wilson.ORMapper;

namespace SimatSoft.DB.ORM
{
	public class Custodian : IObjectHelper, IObjectNotification
	{
		private string iD;
		private string firstName;
		private string lastName;
		private string deptID;
		private string remark;
		private string facCode;

		public string ID
		{
			get { return this.iD; }
            set { this.iD = value; }
		}

		public string FirstName
		{
			get { return this.firstName; }
			set { this.firstName = value; }
		}

		public string LastName
		{
			get { return this.lastName; }
			set { this.lastName = value; }
		}

		public string DeptID
		{
			get { return this.deptID; }
			set { this.deptID = value; }
		}

		public string Remark
		{
			get { return this.remark; }
			set { this.remark = value; }
		}

		public string FacCode
		{
			get { return this.facCode; }
			set { this.facCode = value; }
		}


		#region IObjectHelper Members
		public object this[string memberName]
		{
			get {
				switch (memberName) {
					case "iD": return this.iD;
					case "firstName": return this.firstName;
					case "lastName": return this.lastName;
					case "deptID": return this.deptID;
					case "remark": return this.remark;
					case "facCode": return this.facCode;
					default: throw new Exception("Invalid Member");
				}
			}
			set {
				switch (memberName) {
					case "iD": this.iD = (string) value; break;
					case "firstName": this.firstName = (string) value; break;
					case "lastName": this.lastName = (string) value; break;
					case "deptID": this.deptID = (string) value; break;
					case "remark": this.remark = (string) value; break;
					case "facCode": this.facCode = (string) value; break;
					default: throw new Exception("Invalid Member");
				}
			}
		}
		#endregion

		#region IObjectNotification Members
		public void OnCreated(Transaction transaction)
		{
			// TODO
		}

		public void OnCreating(Transaction transaction)
		{
			// TODO
		}

		public void OnDeleted(Transaction transaction)
		{
			// TODO
		}

		public void OnDeleting(Transaction transaction)
		{
			// TODO
		}

		public void OnMaterialized(System.Data.IDataRecord dataRecord)
		{
			// TODO
		}

		public void OnPersistError(Transaction transaction, Exception exception)
		{
			// TODO
		}

		public void OnUpdated(Transaction transaction)
		{
			// TODO
		}

		public void OnUpdating(Transaction transaction)
		{
			// TODO
		}
		#endregion
	}
}
