//This code was generated by a tool as of 2007-05-24 15:56:06.093.

using System;
using Wilson.ORMapper;

namespace SimatSoft.DB.ORM
{
	public class Reason : IObjectHelper, IObjectNotification
	{
		private string code;
		private string name;

		public string Code
		{
			get { return this.code; }
            set { this.code = value; }
		}

		public string Name
		{
			get { return this.name; }
			set { this.name = value; }
		}


		#region IObjectHelper Members
		public object this[string memberName]
		{
			get {
				switch (memberName) {
					case "code": return this.code;
					case "name": return this.name;
					default: throw new Exception("Invalid Member");
				}
			}
			set {
				switch (memberName) {
					case "code": this.code = (string) value; break;
					case "name": this.name = (string) value; break;
					default: throw new Exception("Invalid Member");
				}
			}
		}
		#endregion

		#region IObjectNotification Members
		public void OnCreated(Transaction transaction)
		{
			// TODO
		}

		public void OnCreating(Transaction transaction)
		{
			// TODO
		}

		public void OnDeleted(Transaction transaction)
		{
			// TODO
		}

		public void OnDeleting(Transaction transaction)
		{
			// TODO
		}

		public void OnMaterialized(System.Data.IDataRecord dataRecord)
		{
			// TODO
		}

		public void OnPersistError(Transaction transaction, Exception exception)
		{
			// TODO
		}

		public void OnUpdated(Transaction transaction)
		{
			// TODO
		}

		public void OnUpdating(Transaction transaction)
		{
			// TODO
		}
		#endregion
	}
}
