//This code was generated by a tool as of 2007-06-10 22:44:24.343.

using System;
using Wilson.ORMapper;

namespace SimatSoft.DB.ORM
{
	public class RunControl : IObjectHelper, IObjectNotification
	{
		private string orderRun;
		private string pORun;
		private string transferRun;
		private string issueRun;

		public string OrderRun
		{
			get { return this.orderRun; }
			set { this.orderRun = value; }
		}

		public string PORun
		{
			get { return this.pORun; }
			set { this.pORun = value; }
		}

		public string TransferRun
		{
			get { return this.transferRun; }
			set { this.transferRun = value; }
		}

		public string IssueRun
		{
			get { return this.issueRun; }
			set { this.issueRun = value; }
		}


		#region IObjectHelper Members
		public object this[string memberName]
		{
			get {
				switch (memberName) {
					case "orderRun": return this.orderRun;
					case "pORun": return this.pORun;
					case "transferRun": return this.transferRun;
					case "issueRun": return this.issueRun;
					default: throw new Exception("Invalid Member");
				}
			}
			set {
				switch (memberName) {
					case "orderRun": this.orderRun = (string) value; break;
					case "pORun": this.pORun = (string) value; break;
					case "transferRun": this.transferRun = (string) value; break;
					case "issueRun": this.issueRun = (string) value; break;
					default: throw new Exception("Invalid Member");
				}
			}
		}
		#endregion

		#region IObjectNotification Members
		public void OnCreated(Transaction transaction)
		{
			// TODO
		}

		public void OnCreating(Transaction transaction)
		{
			// TODO
		}

		public void OnDeleted(Transaction transaction)
		{
			// TODO
		}

		public void OnDeleting(Transaction transaction)
		{
			// TODO
		}

		public void OnMaterialized(System.Data.IDataRecord dataRecord)
		{
			// TODO
		}

		public void OnPersistError(Transaction transaction, Exception exception)
		{
			// TODO
		}

		public void OnUpdated(Transaction transaction)
		{
			// TODO
		}

		public void OnUpdating(Transaction transaction)
		{
			// TODO
		}
		#endregion
	}
}
