//This code was generated by a tool as of 2007-06-19 10:07:00.468.

using System;
using System.Collections;
using Wilson.ORMapper;

namespace SimatSoft.DB.ORM
{
	public class WhGroup : IObjectHelper, IObjectNotification
	{
		private string usGroupID;
		private string usGroupName;
		private string facCode;
		private IList whgroupAccesses; // Supports both ObjectSet and Lazy-Loaded ObjectList

		public string UsGroupID
		{
			get { return this.usGroupID; }
            set { this.usGroupID = value; }
		}

		public string UsGroupName
		{
			get { return this.usGroupName; }
			set { this.usGroupName = value; }
		}

		public string FacCode
		{
			get { return this.facCode; }
			set { this.facCode = value; }
		}

		public IList WhgroupAccesses
		{
			get { return this.whgroupAccesses; }
		}


		#region IObjectHelper Members
		public object this[string memberName]
		{
			get {
				switch (memberName) {
					case "usGroupID": return this.usGroupID;
					case "usGroupName": return this.usGroupName;
					case "facCode": return this.facCode;
					case "whgroupAccesses": return this.whgroupAccesses;
					default: throw new Exception("Invalid Member");
				}
			}
			set {
				switch (memberName) {
					case "usGroupID": this.usGroupID = (string) value; break;
					case "usGroupName": this.usGroupName = (string) value; break;
					case "facCode": this.facCode = (string) value; break;
					case "whgroupAccesses": this.whgroupAccesses = (IList) value; break;
					default: throw new Exception("Invalid Member");
				}
			}
		}
		#endregion

		#region IObjectNotification Members
		public void OnCreated(Transaction transaction)
		{
			// TODO
		}

		public void OnCreating(Transaction transaction)
		{
			// TODO
		}

		public void OnDeleted(Transaction transaction)
		{
			// TODO
		}

		public void OnDeleting(Transaction transaction)
		{
			// TODO
		}

		public void OnMaterialized(System.Data.IDataRecord dataRecord)
		{
			// TODO
		}

		public void OnPersistError(Transaction transaction, Exception exception)
		{
			// TODO
		}

		public void OnUpdated(Transaction transaction)
		{
			// TODO
		}

		public void OnUpdating(Transaction transaction)
		{
			// TODO
		}
		#endregion
	}
}
