//This code was generated by a tool as of 2007-06-14 13:27:20.980.

using System;
using System.Collections;
using Wilson.ORMapper;

//namespace SimatSoft.DB.ORM
//{
//    public class Asset : IObjectHelper, IObjectNotification
//    {
//        private string iD;
//        private string name;
//        private string serialNo;
//        private string modelID;
//        private string deptID;
//        private string floorID;
//        private string buildID;
//        private string areaID;
//        private string reasonCode;
//        private string typeID;
//        private string statusID;
//        private string vendorID;
//        private decimal price;
//        private DateTime warrantyStartDate;
//        private DateTime warrantyEndDate;
//        private string custodianID;
//        private string previosCustodian;
//        private DateTime createdDate;
//        private string userName;
//        private DateTime updateDate;
//        private string remark;
//        private string facCode;
//        private Area areaObject; // Strongly Type as Area if not Lazy-Loading
//        private Status statusObject; // Strongly Type as Status if not Lazy-Loading
//        private Type typeObject; // Strongly Type as Type if not Lazy-Loading
		

//        public string ID
//        {
//            get { return this.iD; }
//            set { this.iD = value; }
//        }

//        public string Name
//        {
//            get { return this.name; }
//            set { this.name = value; }
//        }

//        public string SerialNo
//        {
//            get { return this.serialNo; }
//            set { this.serialNo = value; }
//        }

//        public string ModelID
//        {
//            get { return this.modelID; }
//            set { this.modelID = value; }
//        }

//        public string DeptID
//        {
//            get { return this.deptID; }
//            set { this.deptID = value; }
//        }

//        public string FloorID
//        {
//            get { return this.floorID; }
//            set { this.floorID = value; }
//        }

//        public string BuildID
//        {
//            get { return this.buildID; }
//            set { this.buildID = value; }
//        }

//        public string AreaID
//        {
//            get { return this.areaID; }
//            set { this.areaID = value; }
//        }

//        public string ReasonCode
//        {
//            get { return this.reasonCode; }
//            set { this.reasonCode = value; }
//        }

//        public string TypeID
//        {
//            get { return this.typeID; }
//            set { this.typeID = value; }
//        }

//        public string StatusID
//        {
//            get { return this.statusID; }
//            set { this.statusID = value; }
//        }

//        public string VendorID
//        {
//            get { return this.vendorID; }
//            set { this.vendorID = value; }
//        }

//        public decimal Price
//        {
//            get { return this.price; }
//            set { this.price = value; }
//        }

//        public DateTime WarrantyStartDate
//        {
//            get { return this.warrantyStartDate; }
//            set { this.warrantyStartDate = value; }
//        }

//        public DateTime WarrantyEndDate
//        {
//            get { return this.warrantyEndDate; }
//            set { this.warrantyEndDate = value; }
//        }

//        public string CustodianID
//        {
//            get { return this.custodianID; }
//            set { this.custodianID = value; }
//        }

//        public string PreviosCustodian
//        {
//            get { return this.previosCustodian; }
//            set { this.previosCustodian = value; }
//        }

//        public DateTime CreatedDate
//        {
//            get { return this.createdDate; }
//            set { this.createdDate = value; }
//        }

//        public string UserName
//        {
//            get { return this.userName; }
//            set { this.userName = value; }
//        }

//        public DateTime UpdateDate
//        {
//            get { return this.updateDate; }
//            set { this.updateDate = value; }
//        }

//        public string Remark
//        {
//            get { return this.remark; }
//            set { this.remark = value; }
//        }

//        public string FacCode
//        {
//            get { return this.facCode; }
//            set { this.facCode = value; }
//        }

//        // Return the primary key property from the primary key object
//        public Area AreaObject
//        {
//            get { return this.areaObject; }
//        }

//        // Return the primary key property from the primary key object
//        public Status StatusObject
//        {
//            get { return this.statusObject; }
//        }

//        // Return the primary key property from the primary key object
//        public Type TypeObject
//        {
//            get { return this.typeObject; }
//        }

		


//        #region IObjectHelper Members
//        public object this[string memberName]
//        {
//            get {
//                switch (memberName) {
//                    case "iD": return this.iD;
//                    case "name": return this.name;
//                    case "serialNo": return this.serialNo;
//                    case "modelID": return this.modelID;
//                    case "deptID": return this.deptID;
//                    case "floorID": return this.floorID;
//                    case "buildID": return this.buildID;
//                    case "areaID": return this.areaID;
//                    case "reasonCode": return this.reasonCode;
//                    case "typeID": return this.typeID;
//                    case "statusID": return this.statusID;
//                    case "vendorID": return this.vendorID;
//                    case "price": return this.price;
//                    case "warrantyStartDate": return this.warrantyStartDate;
//                    case "warrantyEndDate": return this.warrantyEndDate;
//                    case "custodianID": return this.custodianID;
//                    case "previosCustodian": return this.previosCustodian;
//                    case "createdDate": return this.createdDate;
//                    case "userName": return this.userName;
//                    case "updateDate": return this.updateDate;
//                    case "remark": return this.remark;
//                    case "facCode": return this.facCode;
//                    case "areaObject": return this.areaObject;
//                    case "statusObject": return this.statusObject;
//                    case "typeObject": return this.typeObject;
					
//                    default: throw new Exception("Invalid Member");
//                }
//            }
//            set {
//                switch (memberName) {
//                    case "iD": this.iD = (string) value; break;
//                    case "name": this.name = (string) value; break;
//                    case "serialNo": this.serialNo = (string) value; break;
//                    case "modelID": this.modelID = (string) value; break;
//                    case "deptID": this.deptID = (string) value; break;
//                    case "floorID": this.floorID = (string) value; break;
//                    case "buildID": this.buildID = (string) value; break;
//                    case "areaID": this.areaID = (string) value; break;
//                    case "reasonCode": this.reasonCode = (string) value; break;
//                    case "typeID": this.typeID = (string) value; break;
//                    case "statusID": this.statusID = (string) value; break;
//                    case "vendorID": this.vendorID = (string) value; break;
//                    case "price": this.price = (decimal) value; break;
//                    case "warrantyStartDate": this.warrantyStartDate = (DateTime) value; break;
//                    case "warrantyEndDate": this.warrantyEndDate = (DateTime) value; break;
//                    case "custodianID": this.custodianID = (string) value; break;
//                    case "previosCustodian": this.previosCustodian = (string) value; break;
//                    case "createdDate": this.createdDate = (DateTime) value; break;
//                    case "userName": this.userName = (string) value; break;
//                    case "updateDate": this.updateDate = (DateTime) value; break;
//                    case "remark": this.remark = (string) value; break;
//                    case "facCode": this.facCode = (string) value; break;
//                    case "areaObject": this.areaObject = (Area) value; break;
//                    case "statusObject": this.statusObject = (Status) value; break;
//                    case "typeObject": this.typeObject = (Type) value; break;
					
//                    default: throw new Exception("Invalid Member");
//                }
//            }
//        }
//        #endregion

//        #region IObjectNotification Members
//        public void OnCreated(Transaction transaction)
//        {
//            // TODO
//        }

//        public void OnCreating(Transaction transaction)
//        {
//            // TODO
//        }

//        public void OnDeleted(Transaction transaction)
//        {
//            // TODO
//        }

//        public void OnDeleting(Transaction transaction)
//        {
//            // TODO
//        }

//        public void OnMaterialized(System.Data.IDataRecord dataRecord)
//        {
//            // TODO
//        }

//        public void OnPersistError(Transaction transaction, Exception exception)
//        {
//            // TODO
//        }

//        public void OnUpdated(Transaction transaction)
//        {
//            // TODO
//        }

//        public void OnUpdating(Transaction transaction)
//        {
//            // TODO
//        }
//        #endregion
//    }
//}

namespace SimatSoft.DB.ORM
{
    public class Asset : IObjectHelper, IObjectNotification
    {
        private string iD;
        private string name;
        private string serialNo;
        private string modelID;
        private string deptID;
        private string floorID;
        private string buildID;
        private string areaID;
        private string reasonCode;
        private string typeID;
        private string statusID;
        private string vendorID;
        private decimal price;
        private DateTime warrantyStartDate;
        private DateTime warrantyEndDate;
        private string custodianID;
        private string previosCustodian;
        private DateTime createdDate;
        private string userName;
        private DateTime updateDate;
        private string remark;
        private string facCode;
        private string customfiled1; //JDEAsset
        private string customfiled2; //Capex No.
        private string customfiled3; //Invoice No.
        private DateTime customfiled4; //Invoice Date
        private string customfiled5; //Quotation No.
        private string customfiled6; //MA contract no.
        private string customfiled7; //PR No.
        private string customfiled8;
        private string customfiled9; //short name
        private DateTime customfiled10; //MA Start Date
        private string customfiled11; //Ma End Date
        private string customfiled12;
        private string customfiled13;
        private string customfiled14;
        private string customfiled15;
        private Area areaObject; // Strongly Type as Area if not Lazy-Loading
        private Status statusObject; // Strongly Type as Status if not Lazy-Loading
        private Type typeObject; // Strongly Type as Type if not Lazy-Loading

        public string ID
        {
            get { return this.iD; }
            set { this.iD = value; }
        }

        public string Name
        {
            get { return this.name; }
            set { this.name = value; }
        }

        public string SerialNo
        {
            get { return this.serialNo; }
            set { this.serialNo = value; }
        }

        public string ModelID
        {
            get { return this.modelID; }
            set { this.modelID = value; }
        }

        public string DeptID
        {
            get { return this.deptID; }
            set { this.deptID = value; }
        }

        public string FloorID
        {
            get { return this.floorID; }
            set { this.floorID = value; }
        }

        public string BuildID
        {
            get { return this.buildID; }
            set { this.buildID = value; }
        }

        public string AreaID
        {
            get { return this.areaID; }
            set { this.areaID = value; }
        }

        public string ReasonCode
        {
            get { return this.reasonCode; }
            set { this.reasonCode = value; }
        }

        public string TypeID
        {
            get { return this.typeID; }
            set { this.typeID = value; }
        }

        public string StatusID
        {
            get { return this.statusID; }
            set { this.statusID = value; }
        }

        public string VendorID
        {
            get { return this.vendorID; }
            set { this.vendorID = value; }
        }

        public decimal Price
        {
            get { return this.price; }
            set { this.price = value; }
        }

        public DateTime WarrantyStartDate
        {
            get { return this.warrantyStartDate; }
            set { this.warrantyStartDate = value; }
        }

        public DateTime WarrantyEndDate
        {
            get { return this.warrantyEndDate; }
            set { this.warrantyEndDate = value; }
        }

        public string CustodianID
        {
            get { return this.custodianID; }
            set { this.custodianID = value; }
        }

        public string PreviosCustodian
        {
            get { return this.previosCustodian; }
            set { this.previosCustodian = value; }
        }

        public DateTime CreatedDate
        {
            get { return this.createdDate; }
            set { this.createdDate = value; }
        }

        public string UserName
        {
            get { return this.userName; }
            set { this.userName = value; }
        }

        public DateTime UpdateDate
        {
            get { return this.updateDate; }
            set { this.updateDate = value; }
        }

        public string Remark
        {
            get { return this.remark; }
            set { this.remark = value; }
        }

        public string FacCode
        {
            get { return this.facCode; }
            set { this.facCode = value; }
        }

        public string Customfiled1
        {
            get { return this.customfiled1; }
            set { this.customfiled1 = value; }
        }

        public string Customfiled2
        {
            get { return this.customfiled2; }
            set { this.customfiled2 = value; }
        }

        public string Customfiled3
        {
            get { return this.customfiled3; }
            set { this.customfiled3 = value; }
        }

        //public string Customfiled4
        //{
        //    get { return this.customfiled4; }
        //    set { this.customfiled4 = value; }
        //}
        // Edit on 27-01-09
        public DateTime Customfiled4
        {
            get { return this.customfiled4; }
            set { this.customfiled4 = value; }
        }

        public string Customfiled5
        {
            get { return this.customfiled5; }
            set { this.customfiled5 = value; }
        }

        public string Customfiled6
        {
            get { return this.customfiled6; }
            set { this.customfiled6 = value; }
        }

        public string Customfiled7
        {
            get { return this.customfiled7; }
            set { this.customfiled7 = value; }
        }

        public string Customfiled8
        {
            get { return this.customfiled8; }
            set { this.customfiled8 = value; }
        }

        public string Customfiled9
        {
            get { return this.customfiled9; }
            set { this.customfiled9 = value; }
        }

        //public string Customfiled10
        //{
        //    get { return this.customfiled10; }
        //    set { this.customfiled10 = value; }
        //}
        // Edit on 27-01-09 
        public DateTime Customfiled10
        {
            get { return this.customfiled10; }
            set { this.customfiled10 = value; }
        }

        public string Customfiled11
        {
            get { return this.customfiled11; }
            set { this.customfiled11 = value; }
        }

        public string Customfiled12
        {
            get { return this.customfiled12; }
            set { this.customfiled12 = value; }
        }

        public string Customfiled13
        {
            get { return this.customfiled13; }
            set { this.customfiled13 = value; }
        }

        public string Customfiled14
        {
            get { return this.customfiled14; }
            set { this.customfiled14 = value; }
        }

        public string Customfiled15
        {
            get { return this.customfiled15; }
            set { this.customfiled15 = value; }
        }
        // Return the primary key property from the primary key object
        public Area AreaObject
        {
            get { return this.areaObject; }
        }

        // Return the primary key property from the primary key object
        public Status StatusObject
        {
            get { return this.statusObject; }
        }

        // Return the primary key property from the primary key object
        public Type TypeObject
        {
            get { return this.typeObject; }
        }


        #region IObjectHelper Members
        public object this[string memberName]
        {
            get
            {
                switch (memberName)
                {
                    case "iD": return this.iD;
                    case "name": return this.name;
                    case "serialNo": return this.serialNo;
                    case "modelID": return this.modelID;
                    case "deptID": return this.deptID;
                    case "floorID": return this.floorID;
                    case "buildID": return this.buildID;
                    case "areaID": return this.areaID;
                    case "reasonCode": return this.reasonCode;
                    case "typeID": return this.typeID;
                    case "statusID": return this.statusID;
                    case "vendorID": return this.vendorID;
                    case "price": return this.price;
                    case "warrantyStartDate": return this.warrantyStartDate;
                    case "warrantyEndDate": return this.warrantyEndDate;
                    case "custodianID": return this.custodianID;
                    case "previosCustodian": return this.previosCustodian;
                    case "createdDate": return this.createdDate;
                    case "userName": return this.userName;
                    case "updateDate": return this.updateDate;
                    case "remark": return this.remark;
                    case "facCode": return this.facCode;
                    case "customfiled1": return this.customfiled1;
                    case "customfiled2": return this.customfiled2;
                    case "customfiled3": return this.customfiled3;
                    case "customfiled4": return this.customfiled4;
                    case "customfiled5": return this.customfiled5;
                    case "customfiled6": return this.customfiled6;
                    case "customfiled7": return this.customfiled7;
                    case "customfiled8": return this.customfiled8;
                    case "customfiled9": return this.customfiled9;
                    case "customfiled10": return this.customfiled10;
                    case "customfiled11": return this.customfiled11;
                    case "customfiled12": return this.customfiled12;
                    case "customfiled13": return this.customfiled13;
                    case "customfiled14": return this.customfiled14;
                    case "customfiled15": return this.customfiled15;
                    case "areaObject": return this.areaObject;
                    case "statusObject": return this.statusObject;
                    case "typeObject": return this.typeObject;
                    default: throw new Exception("Invalid Member");
                }
            }
            set
            {
                

                switch (memberName)
                {  
                    
                    case "iD": this.iD = (string)value; break;
                    case "name": this.name = (string)value; break;
                    case "serialNo": this.serialNo = (string)value; break;
                    case "modelID": this.modelID = (string)value; break;
                    case "deptID": this.deptID = (string)value; break;
                    case "floorID": this.floorID = (string)value; break;
                    case "buildID": this.buildID = (string)value; break;
                    case "areaID": this.areaID = (string)value; break;
                    case "reasonCode": this.reasonCode = (string)value; break;
                    case "typeID": this.typeID = (string)value; break;
                    case "statusID": this.statusID = (string)value; break;
                    case "vendorID": this.vendorID = (string)value; break;
                    case "price": this.price = (decimal)value; break;
                    case "warrantyStartDate": this.warrantyStartDate = (DateTime)value; break;
                    case "warrantyEndDate": this.warrantyEndDate = (DateTime)value; break;
                    case "custodianID": this.custodianID = (string)value; break;
                    case "previosCustodian": this.previosCustodian = (string)value; break;
                    case "createdDate": this.createdDate = (DateTime)value; break;
                    case "userName": this.userName = (string)value; break;
                    case "updateDate": this.updateDate = (DateTime)value; break;
                    case "remark": this.remark = (string)value; break;
                    case "facCode": this.facCode = (string)value; break;
                    case "customfiled1": this.customfiled1 = (string)value; break;
                    case "customfiled2": this.customfiled2 = (string)value; break;
                    case "customfiled3": this.customfiled3 = (string)value; break;
                   // case "customfiled4": this.customfiled4 = (string)value; break;
                    case "customfiled4": this.customfiled4 = (DateTime)value; break;
                    case "customfiled5": this.customfiled5 = (string)value; break;
                    case "customfiled6": this.customfiled6 = (string)value; break;
                    case "customfiled7": this.customfiled7 = (string)value; break;
                    case "customfiled8": this.customfiled8 = (string)value; break;
                    case "customfiled9": this.customfiled9 = (string)value; break;
                   // case "customfiled10": this.customfiled10 = (string)value; break;
                    case "customfiled10": this.customfiled10 = (DateTime)value; break;
                    case "customfiled11": this.customfiled11 = (string)value; break;
                    case "customfiled12": this.customfiled12 = (string)value; break;
                    case "customfiled13": this.customfiled13 = (string)value; break;
                    case "customfiled14": this.customfiled14 = (string)value; break;
                    case "customfiled15": this.customfiled15 = (string)value; break;
                    case "areaObject": this.areaObject = (Area)value; break;
                    case "statusObject": this.statusObject = (Status)value; break;
                    case "typeObject": this.typeObject = (Type)value; break;
                    default: throw new Exception("Invalid Member");
                }
            }
        }
        #endregion

        #region IObjectNotification Members
        public void OnCreated(Transaction transaction)
        {
            // TODO
        }

        public void OnCreating(Transaction transaction)
        {
            // TODO
        }

        public void OnDeleted(Transaction transaction)
        {
            // TODO
        }

        public void OnDeleting(Transaction transaction)
        {
            // TODO
        }

        public void OnMaterialized(System.Data.IDataRecord dataRecord)
        {
            // TODO
        }

        public void OnPersistError(Transaction transaction, Exception exception)
        {
            // TODO
        }

        public void OnUpdated(Transaction transaction)
        {
            // TODO
        }

        public void OnUpdating(Transaction transaction)
        {
            // TODO
        }
        #endregion
    }
}
