//This code was generated by a tool as of 2007-08-22 14:05:28.406.

using System;
using System.Collections;
using Wilson.ORMapper;

namespace SimatSoft.DB.ORM
{
	public class AssetReceive : IObjectHelper, IObjectNotification
	{
		private string poid;
		private string modelID;
		private string assetID;
		private int pOSeq;
		private string serialID;
		private string buildID;
		private string floorID;
		private string areaID;
		private string custodianID;
		private DateTime receiveDate;
		private string userName;
		private string facCode;
		private string remark;
		private Area areaObject; // Strongly Type as Area if not Lazy-Loading
        //private POReceive pOReceiveObject; // Strongly Type as POReceive if not Lazy-Loading
        //private POReceive pOReceiveObject; // Strongly Type as POReceive if not Lazy-Loading
        //private POReceive pOReceiveObject; // Strongly Type as POReceive if not Lazy-Loading

		public string Poid
		{
			get { return this.poid; }
            set { this.poid = value; }
		}

		public string ModelID
		{
			get { return this.modelID; }
			set { this.modelID = value; }
		}

		public string AssetID
		{
			get { return this.assetID; }
			set { this.assetID = value; }
		}

		public int POSeq
		{
			get { return this.pOSeq; }
			set { this.pOSeq = value; }
		}

		public string SerialID
		{
			get { return this.serialID; }
			set { this.serialID = value; }
		}

		public string BuildID
		{
			get { return this.buildID; }
			set { this.buildID = value; }
		}

		public string FloorID
		{
			get { return this.floorID; }
			set { this.floorID = value; }
		}

		public string AreaID
		{
			get { return this.areaID; }
			set { this.areaID = value; }
		}

		public string CustodianID
		{
			get { return this.custodianID; }
			set { this.custodianID = value; }
		}

		public DateTime ReceiveDate
		{
			get { return this.receiveDate; }
			set { this.receiveDate = value; }
		}

		public string UserName
		{
			get { return this.userName; }
			set { this.userName = value; }
		}

		public string FacCode
		{
			get { return this.facCode; }
			set { this.facCode = value; }
		}

		public string Remark
		{
			get { return this.remark; }
			set { this.remark = value; }
		}

		// Return the primary key property from the primary key object
		public Area AreaObject
		{
			get { return this.areaObject; }
		}

        //// Return the primary key property from the primary key object
        //public POReceive POReceiveObject
        //{
        //    get { return this.pOReceiveObject; }
        //}

        //// Return the primary key property from the primary key object
        //public POReceive POReceiveObject
        //{
        //    get { return this.pOReceiveObject; }
        //}

        //// Return the primary key property from the primary key object
        //public POReceive POReceiveObject
        //{
        //    get { return this.pOReceiveObject; }
        //}


		#region IObjectHelper Members
		public object this[string memberName]
		{
			get {
				switch (memberName) {
					case "poid": return this.poid;
					case "modelID": return this.modelID;
					case "assetID": return this.assetID;
					case "pOSeq": return this.pOSeq;
					case "serialID": return this.serialID;
					case "buildID": return this.buildID;
					case "floorID": return this.floorID;
					case "areaID": return this.areaID;
					case "custodianID": return this.custodianID;
					case "receiveDate": return this.receiveDate;
					case "userName": return this.userName;
					case "facCode": return this.facCode;
					case "remark": return this.remark;
					case "areaObject": return this.areaObject;
					default: throw new Exception("Invalid Member");
				}
			}
			set {
				switch (memberName) {
					case "poid": this.poid = (string) value; break;
					case "modelID": this.modelID = (string) value; break;
					case "assetID": this.assetID = (string) value; break;
					case "pOSeq": this.pOSeq = (int) value; break;
					case "serialID": this.serialID = (string) value; break;
					case "buildID": this.buildID = (string) value; break;
					case "floorID": this.floorID = (string) value; break;
					case "areaID": this.areaID = (string) value; break;
					case "custodianID": this.custodianID = (string) value; break;
					case "receiveDate": this.receiveDate = (DateTime) value; break;
					case "userName": this.userName = (string) value; break;
					case "facCode": this.facCode = (string) value; break;
					case "remark": this.remark = (string) value; break;
					case "areaObject": this.areaObject = (Area) value; break;
					default: throw new Exception("Invalid Member");
				}
			}
		}
		#endregion

		#region IObjectNotification Members
		public void OnCreated(Transaction transaction)
		{
			// TODO
		}

		public void OnCreating(Transaction transaction)
		{
			// TODO
		}

		public void OnDeleted(Transaction transaction)
		{
			// TODO
		}

		public void OnDeleting(Transaction transaction)
		{
			// TODO
		}

		public void OnMaterialized(System.Data.IDataRecord dataRecord)
		{
			// TODO
		}

		public void OnPersistError(Transaction transaction, Exception exception)
		{
			// TODO
		}

		public void OnUpdated(Transaction transaction)
		{
			// TODO
		}

		public void OnUpdating(Transaction transaction)
		{
			// TODO
		}
		#endregion
	}
}
