//This code was generated by a tool as of 2007-06-01 16:44:53.171.

using System;
using Wilson.ORMapper;

namespace SimatSoft.DB.ORM
{
	public class CheckStock : IObjectHelper, IObjectNotification
	{
		private string assetID;
		private string modelID;
		private string buildID;
		private string floorID;
		private string areaID;
		private string serialNo;
		private string remark;
		private string type;
		private string userName;
		private DateTime createdDate;
		private string facCode;

		public string AssetID
		{
			get { return this.assetID; }
			set { this.assetID = value; }
		}

		public string ModelID
		{
			get { return this.modelID; }
			set { this.modelID = value; }
		}

		public string BuildID
		{
			get { return this.buildID; }
			set { this.buildID = value; }
		}

		public string FloorID
		{
			get { return this.floorID; }
			set { this.floorID = value; }
		}

		public string AreaID
		{
			get { return this.areaID; }
			set { this.areaID = value; }
		}

		public string SerialNo
		{
			get { return this.serialNo; }
			set { this.serialNo = value; }
		}

		public string Remark
		{
			get { return this.remark; }
			set { this.remark = value; }
		}

		public string Type
		{
			get { return this.type; }
			set { this.type = value; }
		}

		public string UserName
		{
			get { return this.userName; }
			set { this.userName = value; }
		}

		public DateTime CreatedDate
		{
			get { return this.createdDate; }
			set { this.createdDate = value; }
		}

		public string FacCode
		{
			get { return this.facCode; }
			set { this.facCode = value; }
		}


		#region IObjectHelper Members
		public object this[string memberName]
		{
			get {
				switch (memberName) {
					case "assetID": return this.assetID;
					case "modelID": return this.modelID;
					case "buildID": return this.buildID;
					case "floorID": return this.floorID;
					case "areaID": return this.areaID;
					case "serialNo": return this.serialNo;
					case "remark": return this.remark;
					case "type": return this.type;
					case "userName": return this.userName;
					case "createdDate": return this.createdDate;
					case "facCode": return this.facCode;
					default: throw new Exception("Invalid Member");
				}
			}
			set {
				switch (memberName) {
					case "assetID": this.assetID = (string) value; break;
					case "modelID": this.modelID = (string) value; break;
					case "buildID": this.buildID = (string) value; break;
					case "floorID": this.floorID = (string) value; break;
					case "areaID": this.areaID = (string) value; break;
					case "serialNo": this.serialNo = (string) value; break;
					case "remark": this.remark = (string) value; break;
					case "type": this.type = (string) value; break;
					case "userName": this.userName = (string) value; break;
					case "createdDate": this.createdDate = (DateTime) value; break;
					case "facCode": this.facCode = (string) value; break;
					default: throw new Exception("Invalid Member");
				}
			}
		}
		#endregion

		#region IObjectNotification Members
		public void OnCreated(Transaction transaction)
		{
			// TODO
		}

		public void OnCreating(Transaction transaction)
		{
			// TODO
		}

		public void OnDeleted(Transaction transaction)
		{
			// TODO
		}

		public void OnDeleting(Transaction transaction)
		{
			// TODO
		}

		public void OnMaterialized(System.Data.IDataRecord dataRecord)
		{
			// TODO
		}

		public void OnPersistError(Transaction transaction, Exception exception)
		{
			// TODO
		}

		public void OnUpdated(Transaction transaction)
		{
			// TODO
		}

		public void OnUpdating(Transaction transaction)
		{
			// TODO
		}
		#endregion
	}
}
