//This code was generated by a tool as of 2007-05-24 15:51:30.781.

using System;
using System.Collections;
using Wilson.ORMapper;

namespace SimatSoft.DB.ORM
{
	public class Model : IObjectHelper, IObjectNotification
	{
		private string iD;
		private string name;
        private string brand;
        private decimal value;

		public string ID
		{
			get { return this.iD; }
            set { this.iD = value; }
		}

		public string Name
		{
			get { return this.name; }
			set { this.name = value; }
		}
        public string Brand
        {
            get { return this.brand; }
            set { this.brand = value; }
        }

		public decimal Value
		{
			get { return this.value; }
			set { this.value = value; }
		}

		
		#region IObjectHelper Members
		public object this[string memberName]
		{
			get {
				switch (memberName) {
					case "iD": return this.iD;
					case "name": return this.name;
                    case "brand": return this.brand;
                    case "value": return this.value;
					
					default: throw new Exception("Invalid Member");
				}
			}
			set {
				switch (memberName) {
					case "iD": this.iD = (string) value; break;
					case "name": this.name = (string) value; break;
                    case "brand": this.brand = (string)value; break;
                    case "value": this.value = (decimal)value; break;
					
					default: throw new Exception("Invalid Member");
				}
			}
		}
		#endregion

		#region IObjectNotification Members
		public void OnCreated(Transaction transaction)
		{
			// TODO
		}

		public void OnCreating(Transaction transaction)
		{
			// TODO
		}

		public void OnDeleted(Transaction transaction)
		{
			// TODO
		}

		public void OnDeleting(Transaction transaction)
		{
			// TODO
		}

		public void OnMaterialized(System.Data.IDataRecord dataRecord)
		{
			// TODO
		}

		public void OnPersistError(Transaction transaction, Exception exception)
		{
			// TODO
		}

		public void OnUpdated(Transaction transaction)
		{
			// TODO
		}

		public void OnUpdating(Transaction transaction)
		{
			// TODO
		}
		#endregion
	}
}
