//This code was generated by a tool as of 2007-05-24 15:57:18.062.

using System;
using System.Collections;
using Wilson.ORMapper;

namespace SimatSoft.DB.ORM
{
	public class Status : IObjectHelper, IObjectNotification
	{
		private string iD;
		private string name;
		

		public string ID
		{
			get { return this.iD; }
            set { this.iD = value; }
		}

		public string Name
		{
			get { return this.name; }
			set { this.name = value; }
		}

		

		#region IObjectHelper Members
		public object this[string memberName]
		{
			get {
				switch (memberName) {
					case "iD": return this.iD;
					case "name": return this.name;
					default: throw new Exception("Invalid Member");
				}
			}
			set {
				switch (memberName) {
					case "iD": this.iD = (string) value; break;
					case "name": this.name = (string) value; break;
					default: throw new Exception("Invalid Member");
				}
			}
		}
		#endregion

		#region IObjectNotification Members
		public void OnCreated(Transaction transaction)
		{
			// TODO
		}

		public void OnCreating(Transaction transaction)
		{
			// TODO
		}

		public void OnDeleted(Transaction transaction)
		{
			// TODO
		}

		public void OnDeleting(Transaction transaction)
		{
			// TODO
		}

		public void OnMaterialized(System.Data.IDataRecord dataRecord)
		{
			// TODO
		}

		public void OnPersistError(Transaction transaction, Exception exception)
		{
			// TODO
		}

		public void OnUpdated(Transaction transaction)
		{
			// TODO
		}

		public void OnUpdating(Transaction transaction)
		{
			// TODO
		}
		#endregion
	}
}
