//This code was generated by a tool as of 2007-06-18 15:14:58.406.

using System;
using System.Collections;
using Wilson.ORMapper;

namespace SimatSoft.DB.ORM
{
	public class SysScreenSubType : IObjectHelper, IObjectNotification
	{
		private string sCsubType;
		private string scsubTypeDe;
		private IList screens; // Supports both ObjectSet and Lazy-Loaded ObjectList

		public string SCsubType
		{
			get { return this.sCsubType; }
		}

		public string ScsubTypeDe
		{
			get { return this.scsubTypeDe; }
			set { this.scsubTypeDe = value; }
		}

		public IList Screens
		{
			get { return this.screens; }
		}


		#region IObjectHelper Members
		public object this[string memberName]
		{
			get {
				switch (memberName) {
					case "sCsubType": return this.sCsubType;
					case "scsubTypeDe": return this.scsubTypeDe;
					case "screens": return this.screens;
					default: throw new Exception("Invalid Member");
				}
			}
			set {
				switch (memberName) {
					case "sCsubType": this.sCsubType = (string) value; break;
					case "scsubTypeDe": this.scsubTypeDe = (string) value; break;
					case "screens": this.screens = (IList) value; break;
					default: throw new Exception("Invalid Member");
				}
			}
		}
		#endregion

		#region IObjectNotification Members
		public void OnCreated(Transaction transaction)
		{
			// TODO
		}

		public void OnCreating(Transaction transaction)
		{
			// TODO
		}

		public void OnDeleted(Transaction transaction)
		{
			// TODO
		}

		public void OnDeleting(Transaction transaction)
		{
			// TODO
		}

		public void OnMaterialized(System.Data.IDataRecord dataRecord)
		{
			// TODO
		}

		public void OnPersistError(Transaction transaction, Exception exception)
		{
			// TODO
		}

		public void OnUpdated(Transaction transaction)
		{
			// TODO
		}

		public void OnUpdating(Transaction transaction)
		{
			// TODO
		}
		#endregion
	}
}
